#!/usr/bin/env python3
"""
Quick Email Setup Script for NOVA
This script helps you set up email for 2-step verification
"""

import os

def create_env_file():
    """Create or update .env file with email configuration"""
    env_file = '.env'
    
    print("=" * 60)
    print("📧 NOVA Email Setup for 2-Step Verification")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    if os.path.exists(env_file):
        print(f"⚠️  {env_file} already exists.")
        response = input("Do you want to update it? (y/n): ").lower()
        if response != 'y':
            print("Cancelled.")
            return
        print()
    
    # Get email configuration
    print("Enter your email configuration:")
    print()
    
    email_enabled = input("Enable email? (y/n) [y]: ").lower() or 'y'
    email_enabled = 'true' if email_enabled == 'y' else 'false'
    
    if email_enabled == 'true':
        print()
        print("Email Provider:")
        print("1. Gmail (recommended)")
        print("2. Outlook/Hotmail")
        print("3. Yahoo")
        print("4. Custom SMTP")
        provider = input("Choose provider [1]: ").strip() or '1'
        
        if provider == '1':
            smtp_server = 'smtp.gmail.com'
            smtp_port = '587'
        elif provider == '2':
            smtp_server = 'smtp-mail.outlook.com'
            smtp_port = '587'
        elif provider == '3':
            smtp_server = 'smtp.mail.yahoo.com'
            smtp_port = '587'
        else:
            smtp_server = input("SMTP Server: ").strip()
            smtp_port = input("SMTP Port [587]: ").strip() or '587'
        
        print()
        email_sender = input("Your email address: ").strip()
        print()
        print("For Gmail: Use an App Password (not your regular password)")
        print("Get one at: https://myaccount.google.com/apppasswords")
        print()
        email_password = input("Email password/App Password: ").strip()
        
        use_tls = input("Use TLS? (y/n) [y]: ").lower() or 'y'
        use_tls = 'true' if use_tls == 'y' else 'false'
    else:
        smtp_server = 'smtp.gmail.com'
        smtp_port = '587'
        email_sender = ''
        email_password = ''
        use_tls = 'true'
    
    # Write .env file
    env_content = f"""# NOVA Email Configuration
# Generated by setup_email.py

EMAIL_ENABLED={email_enabled}
EMAIL_SMTP_SERVER={smtp_server}
EMAIL_SMTP_PORT={smtp_port}
EMAIL_USE_TLS={use_tls}
EMAIL_SENDER={email_sender}
EMAIL_PASSWORD={email_password}
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print()
    print("=" * 60)
    print("✅ .env file created successfully!")
    print("=" * 60)
    print()
    
    if email_enabled == 'true':
        print("📧 Email is ENABLED")
        print("   Verification codes will be sent to user emails")
        print()
        print("⚠️  IMPORTANT: Restart your backend server for changes to take effect!")
        print("   Run: python3 app.py")
    else:
        print("📧 Email is DISABLED")
        print("   Codes will be shown in console/response (dev mode)")
    print()

if __name__ == '__main__':
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\nCancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
